# Generated by Django 4.1.7 on 2023-03-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cakes_cake_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='shape',
            field=models.CharField(blank=True, choices=[('round', 'round'), ('square', 'square'), ('heart', 'heart')], default='round', max_length=200, null=True),
        ),
    ]
